# The `demo` environment — the catstack `infra_environments/` role. Every domain
# function receives this attrset as `env`.
#
# THIS REPO IS PUBLIC. Every account-specific value below is deliberately FAKE.
# That is the end state, not a TODO — but you do not edit this file to change it.
# Account-specific values are declared as nivis configuration *variables* with a
# fake default; supply your own at run time, without touching a tracked file:
#
#   environments/demo.vars.json      (gitignored; ./stackctl passes --var-file)
#   NIVIS_VAR_stateBucket=...        (environment)
#   ./stackctl demo 000_backend plan --var stateBucket=...   (one-off, wins)
#
# Credentials never appear here or in a vars file — they come from the standard
# chains (AWS profile / environment, HCLOUD_TOKEN). Secrets proper go through
# agenix (see secrets/), never through a variable.
{
  name = "demo";

  # Variable DECLARATIONS. Domains resolve these per run with
  # `nivis.mkVars env.vars (ledger.vars or { })`; a declaration with no default
  # is required and fails by name when unset.
  vars = {
    # FAKE ON PURPOSE, and deliberately *invalid*: `_` and uppercase are outside
    # S3's bucket-naming grammar, so AWS rejects it immediately instead of
    # creating something under a name you did not choose. A plausible-looking
    # name would be squattable, turning every clone's first apply into a
    # confusing BucketAlreadyExists from a bucket nobody here controls.
    stateBucket = {
      type = "str";
      default = "REPLACE_ME-nivis-demos-state";
    };

    # REQUIRED — no default, deliberately. Every other variable here carries a
    # fake default because a fake value fails harmlessly: an invalid bucket name
    # is simply rejected by S3. That reasoning does not extend to a domain name.
    # Any syntactically valid placeholder is a name somebody else owns, and a
    # certificate would be requested for it. So this fails by name when unset:
    #
    #   nivis.mkVars: variable 'domain' is required (no default) and was not set
    #
    # Supply it per run — never in a tracked file (this repo is public, and a
    # hostname is exactly what must not land in it):
    #
    #   echo '{ "domain": "demo.example.com" }' > environments/demo.vars.json
    #   ./stackctl demo 010_dns apply --var domain=demo.example.com
    domain = {
      type = "str";
    };

    # The region is a variable, not a literal, for two reasons: it was
    # previously written twice (provider and state backend) with nothing keeping
    # them in step — create resources in one region, write state to a bucket in
    # another — and a clone elsewhere in the world should not have to edit a
    # tracked file to move. A default is safe here, unlike `domain` and
    # `awsAccountId`, where guessing is the failure mode.
    #
    # Changing this after the state bucket exists points the backend at a
    # different region, where your state is not: migrate deliberately.
    awsRegion = {
      type = "str";
      default = "eu-central-1";
    };

    # REQUIRED — which AWS account these demos may touch.
    #
    # Nothing else pins this: AWS credentials are just "whatever identity is
    # loaded", so without this guard an apply lands in whichever account you
    # happen to be authenticated to. It is wired to the provider's
    # `allowed_account_ids`, so a wrong-account run fails at PLAN time having
    # created nothing. No default, because guessing here is exactly the failure
    # mode. Supply it alongside `domain` in environments/demo.vars.json.
    awsAccountId = {
      type = "str";
    };

    # Distinguishes this stack's globally-scoped AWS names (the vmimport role,
    # the image bucket, the AMI) so two demos can coexist in one account.
    suffix = {
      type = "str";
      default = "demo";
    };

    instanceType = {
      type = "str";
      default = "t3.small";
    };

    dataVolumeSizeGb = {
      type = "int";
      default = 8;
    };

    # --- Hetzner ---------------------------------------------------------
    # A Hetzner API token is scoped to one project by construction, so unlike
    # AWS there is no account to pin: whichever token you export IS the guard.
    hcloudLocation = {
      type = "str";
      default = "fsn1";
    };

    # x86, deliberately diverging from the infra repo's ARM. The image then
    # builds natively on any x86_64 machine, instead of needing binfmt
    # emulation or a remote builder just to try the demo.
    hcloudServerType = {
      type = "str";
      default = "cx22";
    };

    # Primary IPs are datacenter-scoped, not location-scoped, so this is a
    # separate value from hcloudLocation and must sit inside it.
    hcloudDatacenter = {
      type = "str";
      default = "fsn1-dc14";
    };

    hetznerVolumeSizeGb = {
      type = "int";
      default = 10; # Hetzner's minimum volume size
    };
  };

  # Remote state (the catstack .tfbackend role). The bucket comes from the
  # `stateBucket` variable, so overriding it moves both the bucket resource and
  # the backend together; each domain appends its own `key`.
  backend = {
    type = "s3";
    # `bucket` and `region` are filled in by each domain from the resolved
    # variables, so the provider and the state backend can never disagree.
  };

  tags = {
    ManagedBy = "nivis";
    Project = "nivis-demos";
    Environment = "demo";
  };
}
