# The `demo` environment — the catstack `infra_environments/` role. Every domain
# function receives this attrset as `env`.
#
# THIS REPO IS PUBLIC. Every account-specific value below is deliberately FAKE.
# That is the end state, not a TODO — but you do not edit this file to change it.
# Account-specific values are declared as nivis configuration *variables* with a
# fake default; supply your own at run time, without touching a tracked file:
#
#   environments/demo.vars.json      (gitignored; ./stackctl passes --var-file)
#   NIVIS_VAR_stateBucket=...        (environment)
#   ./stackctl demo 000_backend plan --var stateBucket=...   (one-off, wins)
#
# Credentials never appear here or in a vars file — they come from the standard
# chains (AWS profile / environment, HCLOUD_TOKEN). Secrets proper go through
# agenix (see secrets/), never through a variable.
{
  name = "demo";

  aws = {
    # Safe to publish: a region is not account-specific.
    region = "eu-central-1";
  };

  # Variable DECLARATIONS. Domains resolve these per run with
  # `nivis.mkVars env.vars (ledger.vars or { })`; a declaration with no default
  # is required and fails by name when unset.
  vars = {
    # FAKE ON PURPOSE, and deliberately *invalid*: `_` and uppercase are outside
    # S3's bucket-naming grammar, so AWS rejects it immediately instead of
    # creating something under a name you did not choose. A plausible-looking
    # name would be squattable, turning every clone's first apply into a
    # confusing BucketAlreadyExists from a bucket nobody here controls.
    stateBucket = {
      type = "str";
      default = "REPLACE_ME-nivis-demos-state";
    };
  };

  # Remote state (the catstack .tfbackend role). The bucket comes from the
  # `stateBucket` variable, so overriding it moves both the bucket resource and
  # the backend together; each domain appends its own `key`.
  backend = {
    type = "s3";
    region = "eu-central-1";
  };

  tags = {
    ManagedBy = "nivis";
    Project = "nivis-demos";
    Environment = "demo";
  };
}
